export const AUTH_LOGIN_INIT = 'AUTH_LOGIN_INIT'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const PRODUCT_LOADED_INIT = 'PRODUCT_LOADED_INIT'
export const PRODUCTS_LOADED_SUCCESS = 'PRODUCTS_LOADED_SUCCESS'
export const PRODUCTS_LOADED_FAILURE = 'PRODUCTS_LOADED_FAILURE'

export const PRODUCT_CREATED_INIT = 'PRODUCT_CREATED_INIT'
export const PRODUCT_CREATED_SUCCESS = 'PRODUCT_CREATED_SUCCESS'
export const PRODUCT_CREATED_FAILURE = 'PRODUCT_CREATED_FAILURE'


export const PRODUCT_DETAILS_INIT = 'PRODUCT_DETAILS_INIT'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAILURE = 'PRODUCT_DETAILS_FAILURE'


export const PRODUCT_REMOVE_INIT = 'PRODUCT_REMOVE_INIT'
export const PRODUCT_REMOVE_SUCCESS = 'PRODUCT_REMOVE_SUCCESS'
export const PRODUCT_REMOVE_FAILURE = 'PRODUCT_REMOVE_FAILURE'


//TAGS

export const RESET_ERROR = 'RESET_ERROR';


