export const AUTH_LOGIN_INIT = 'AUTH_LOGIN_INIT'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const PRODUCT_LOADED_INIT = 'PRODUCT_LOADED_INIT'
export const PRODUCTS_LOADED_SUCCESS = 'PRODUCTS_LOADED_SUCCESS'
export const PRODUCTS_LOADED_FAILURE = 'PRODUCTS_LOADED_FAILURE'

export const PRODUCT_CREATED_INIT = 'PRODUCT_CREATED'
export const PRODUCT_CREATED_SUCCESS = 'PRODUCT_CREATED_SUCCESS'
export const PRODUCT_CREATED_FAILURE = 'PRODUCT_CREATED_FAILURE'

export const RESET_ERROR = 'RESET_ERROR';


